apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbx-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/cluster/data/rbx-volume"
