apiVersion: v1
kind: Pod
metadata:
  name: met-pod
  labels: 
    app: met-pod-app
spec:
  containers:
  - name: met-pod-nginx
    image: nginx:stable
    ports:
    - containerPort: 8081
      name: met-pod-port
    volumeMounts:
    - name: met-configmap
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes:
  - name: met-configmap
    configMap:
      name: met-configmap
