apiVersion: v1
kind: Service
metadata:
  name: met-svc
spec:
  type: ClusterIP
  externalIPs:
    - 84.247.161.33
  selector:
    app: met
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
