apiVersion: v1
kind: Service
metadata:
  name: met-svc
spec:
  type: ExternalName
  externalName: host.docker.internal
  selector:
    app: met
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
