apiVersion: v1
kind: ConfigMap
metadata:
  name: met-configmap
data:
  nginx.conf: |
    server {
        listen 8069;

        location / {
            proxy_pass http://84.247.161.33:8069;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
