apiVersion: apps/v1
kind: Deployment
metadata:
  name: tur-deploy
spec:
  selector:
    matchLabels:
      app: tur-deploy
  template:
    metadata:
      labels:
        app: tur-deploy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: tur-deploy
          image: ldamasio/turno:latest
          command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
          ports:
          - containerPort: 8000
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
