apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rab-rabbitmq-cluster
spec:
  replicas: 1
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
