apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gze-man-prod-cert
  namespace: gze
spec:
  secretName: gze-man-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - $DB_HOSTNAME
