apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lda-frontend-prod-ingress
spec:
  rules:
  - host: leandrodamasio.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lda-frontend-prod-svc
            port:
              number: 80

