apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbs-frontend-ingress
    annotations:
      cert-manager.io/cluster-issuer: "rbs-lets-encrypt"
      spec.ingressClassName: "public"
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - www.robsonbot.com
    secretName: rbs-frontend-prod-tls
  rules:
  - host: www.robsonbot.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rbs-frontend-svc
            port:
              number: 80

