apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbs-backend-monolith-prod-deploy
  labels:
    app: rbs-backend-monolith-prod-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbs-backend-monolith-prod-deploy
  template:
    metadata:
      labels:
        app: rbs-backend-monolith-prod-deploy
    spec:
      containers:
      - name: rbs-backend-monolith-prod-deploy
        image: ldamasio/lda-backend-monolith:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"

