apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbs-backend-prod-nginx
  labels:
    app: rbs-backend-prod-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbs-backend-prod-nginx
  template:
    metadata:
      labels:
        app: rbs-backend-prod-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
