apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbs-backend-prod-nginx-deploy
  labels:
    app: rbs-backend-prod-nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbs-backend-prod-nginx-deploy
  template:
    metadata:
      labels:
        app: rbs-backend-prod-nginx-deploy
    spec:
      initContainers:
      containers:
      - name: rbs-backend-prod-nginx-deploy
        image: ldamasio/rbs-backend-nginx-prod
        ports:
        - containerPort: 80
        volumeMounts:
        - name: rbs-backend-nginx-prod-configmap
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: rbs-backend-nginx-prod-configmap
          configMap:
            name: rbs-backend-nginx-prod-configmap
