apiVersion: v1
kind: ConfigMap
metadata:
  name: rbs-backend-nginx-prod-configmap
data:
  nginx.conf: |
    server {
      listen 8080;

      location /static/ {
        alias /static/;
      }

      location / {
        proxy_pass http://rbs-backend-monolith-prod-svc:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
