apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vit
  namespace: default
spec:
  source:
    repoURL: https://github.com/ldamasio/vit
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: vit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

