apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cro-frontend-prod-cert
spec:
  secretName: cro-frontend-prod-cert
  issuerRef:
    name: cro-frontend-prod-issuer
  dnsNames:
  - cromo.rbxrobotica.com.br
