apiVersion: apps/v1
kind: Deployment
metadata:
  name: cro-backend-prod-deploy
spec:
  selector:
    matchLabels:
      app: cro-backend-prod-deploy
  template:
    metadata:
      labels:
        app: cro-backend-prod-deploy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: cro-backend-prod-deploy
          image: ldamasio/cro-backend-prod:latest
          env:
          - name: DJANGO_SETTINGS_MODULE
            value: "backend.settings"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: cro-django-secret
                key: SECRET_KEY
          ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "1000Mi"
            cpu: "750m"
          limits:
            memory: "1000Mi"
            cpu: "1500m"
