apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbx-frontend-deploy
spec:
  selector:
    matchLabels:
      app: rbx-frontend-prod-deploy
  template:
    metadata:
      labels:
        app: rbx-frontend-prod-deploy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3404"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: rbx-frontend-prod-deploy
        image: ldamasio/rbx-frontend:latest
        ports:
          -  containerPort: 8000
        volumeMounts:
          - name: rbx-share
            mountPath: /usr/share/nginx/html
