apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rab-rabbitmq-cluster
spec:
  replicas: 1
  podSpec:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 1Gi
